CONFIG_ZMK_KEYBOARD_NAME="SithLilly"

# Encoder support
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# RGB underglow - disabled
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
#CONFIG_LED_STRIP=n

# Bluetooth power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Deep sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Get around Intel AX211 Bluetooth driver issue
# CONFIG_BT_CTLR_PHY_2M=n
